### PR TITLE
Add windows executable

### PR DESCRIPTION
**Pull request by DenisMot**
Hi Germain
Could you add the your .exe to this branch ? 
I modified the readme.md to account ofr this add. 
Denis

### CODE REVIEW

**Comment by gfaity** [comment]
Hi Denis,
I just replaced the .txt by the .exe for windows in release directory. Please tell me if the commit works.
Germain

**Comment by DenisMot** [comment]
Germain, 
I see version 1 in the exe, but we need version 1.1, so to keep the exe coherent with the rest of the repository. Can you rebuild the exe with the most up to date version of the code ?

**Comment by DenisMot** [comment]
Also, I cannot see the .csv output, which I expect to be located next to the .exe

**Comment by gfaity** [comment]
I have just rebuilt and updated the .exe with v1.1.0.
I have also tried to perform the circular steering task in my local github repository and data.csv and marker.csv have been successfully exported in RELEASE directory.
Job should be done !

**Comment by gfaity** [comment]
Here is a screenshot of what I have 
image

**Pull request merged**
